{{- $serviceName := (printf "wordpress-%s" .Release.Name | trunc 63 | trimSuffix "-") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: {{ template "d4-wordpress-chart.fullname" . }}
spec:
  backend:
    serviceName: {{ $serviceName }}
    servicePort: 80

  tls:
    - secretName: {{ .Release.Name }}-ingress-certs
      hosts:
    {{- range .Values.domains }}
      - {{ . }}
    {{- end }}
