apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
  name: {{ template "d4-wordpress-chart.fullname" . }}
spec:
  rules:
  - host: {{ .Release.Name }}.directivefour.com
    http:
      paths:
      - backend:
          serviceName: {{ template "d4-wordpress-chart.fullname" . }}
          servicePort: 80

  tls:
  - secretName: {{ .Release.Name }}-directivefour-com-keys-ingress
    hosts:
    - {{ .Release.Name }}.directivefour.com
