apiVersion: v1
kind: Secret
metadata:
  name: {{ template "d4-wordpress-chart.fullname" . }}
  labels:
    app: {{ template "d4-wordpress-chart.fullname" . }}
    chart: {{ template "d4-wordpress-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  mysql-user: {{ randAlphaNum 16 | b64enc | quote }}
