apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "d4-wordpress-chart.fullname" . }}
  name: {{ template "d4-wordpress-chart.fullname" . }}
spec:
  ports:
  - port: 80
  selector:
    app: {{ template "d4-wordpress-chart.fullname" . }}
  sessionAffinity: None
